Use the kernel with bundled initramfs
resin-os/resin-artik pull request #70
Opened 2017-03-14 08:44 UTC by floion

2017-03-14 09:11 UTC, michal-mazurek approved these changes

2017-03-14 10:28 UTC, telphan approved these changes

2017-03-14 14:42 UTC, floion commented
The artik10 doesn't boot this kernel. On the serial debug console I can see the log saying "Starting kernel" and that is all. Needs more investigation

2017-03-14 15:57 UTC, agherzan approved these changes

2017-03-15 19:12 UTC, agherzan requested changes
You are updating meta-resin to a new version so you need to bump VERSION too.

2017-03-16 07:29 UTC, agherzan approved these changes

2017-03-17 10:21 UTC, merged